/*
 *  Copyright © 2018 Robin Weiss (http://www.gerdi-project.de/)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package de.gerdiproject.application;

import static org.junit.Assert.assertTrue;

import java.io.File;

import org.junit.Test;

import de.gerdiproject.AbstractUnitTest;
import de.gerdiproject.application.examples.MockedContextListener;
import de.gerdiproject.harvest.application.MainContext;
import de.gerdiproject.harvest.application.events.ServiceInitializedEvent;
import de.gerdiproject.harvest.utils.file.FileUtils;

/**
 * This class offers unit tests for the {@linkplain MainContext}.
 *
 * @author Robin Weiss
 */
public class MainContextTest extends AbstractUnitTest
{
    private static final int INIT_TIMEOUT = 5000;
    private static final File CACHE_FOLDER = new File("cache");
    private static final String CLEANUP_ERROR = "Could not delete temporary test directory for MainContext tests: " + CACHE_FOLDER;


    @Override
    public void before() throws InstantiationException
    {
        // remove cache folder that is generated by the MainContext
        FileUtils.deleteFile(CACHE_FOLDER);

        if (CACHE_FOLDER.exists())
            throw new InstantiationException(CLEANUP_ERROR);

        super.before();
    }


    @Override
    public void after()
    {
        super.after();

        // clean up temp files after tests to free up some space
        FileUtils.deleteFile(CACHE_FOLDER);
    }


    /**
     * Tests if the init() method ultimately sends a {@linkplain ServiceInitializedEvent}
     * that marks the initialization as successful.
     */
    @Test
    public void testInitialization()
    {
        final MockedContextListener mockedContextListener = new MockedContextListener();

        ServiceInitializedEvent initDoneEvent = waitForEvent(
                                                    ServiceInitializedEvent.class,
                                                    INIT_TIMEOUT,
                                                    () -> mockedContextListener.contextInitialized(null));

        assertTrue("Expected the method init() to send an event marking the initialization as successful!",
                   initDoneEvent.isSuccessful());
    }
}
